package il.ac.shenkar.java.costmanager.domain.model;

/**
 * The `Category` class represents a category for expenses.
 * Each category has a unique ID generated by the DerbyDB and a name.
 */
public class Category {
    private int id;
    private String name;

    /**
     * Constructs a new Category with the given name.
     *
     * @param name The name of the category.
     */
    public Category(String name) {
        setName(name);
    }

    /**
     * Gets the unique ID of the category.
     *
     * @return The ID of the category.
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the ID of the category.
     * This method validates that the ID is non-negative.
     *
     * @param id The ID to set.
     */
    public void setId(int id) {
        try {
            if (id >= 0) {
                this.id = id;
            } else {
                throw new IllegalArgumentException("ID should contain only non-negative integers.");
            }
        } catch (IllegalArgumentException e) {
            System.err.println("Invalid ID: " + e.getMessage());
        }
    }

    /**
     * Gets the name of the category.
     *
     * @return The name of the category.
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the category.
     * This method validates that the name contains only alphabetic characters (a-z, A-Z).
     *
     * @param name The name to set.
     */
    private void setName(String name) {
        try {
            if (name.matches("^[a-zA-Z]+[0-9]*$")) {
                this.name = name;
            } else {
                throw new IllegalArgumentException("Name should contain only alphabetic characters (a-z, A-Z).");
            }
        } catch (IllegalArgumentException e) {
            System.err.println("Invalid name: " + e.getMessage());
        }
    }
}
